// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertNumber(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertNumber'](arg1, arg2, arg3);
}

export function ConvertToAllSystems(arg1, arg2) {
  return window['go']['main']['App']['ConvertToAllSystems'](arg1, arg2);
}
