// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertNumber(arg1:string,arg2:number,arg3:number):Promise<main.ConversionResult>;

export function ConvertToAllSystems(arg1:string,arg2:number):Promise<main.AllConversionsResult>;
